after-login-command = []
after-startup-command = []
start-at-login = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true 

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

[mode.main.binding]

# Meh bindings
alt-ctrl-shift-h = 'move left'
alt-ctrl-shift-j = 'move down'
alt-ctrl-shift-k = 'move up'
alt-ctrl-shift-l = 'move right'

# Hyper bindings
alt-ctrl-cmd-shift-h = 'focus left'
alt-ctrl-cmd-shift-j = 'focus down'
alt-ctrl-cmd-shift-k = 'focus up'
alt-ctrl-cmd-shift-l = 'focus right'
alt-ctrl-cmd-shift-u = 'resize smart +50'
alt-ctrl-cmd-shift-i = 'resize smart -50'
alt-ctrl-cmd-shift-m = 'layout tiles horizontal vertical'
alt-ctrl-cmd-shift-n = 'layout accordion horizontal vertical'
alt-ctrl-cmd-shift-semicolon = 'mode service'

f13 = 'workspace 1'
f14 = 'workspace 2'
f15 = 'workspace 3'
shift-f13 = 'move-node-to-workspace 1'
shift-f14 = 'move-node-to-workspace 2'
shift-f15 = 'move-node-to-workspace 3'

alt-tab = 'workspace-back-and-forth'


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-ctrl-cmd-shift-h = ['join-with left', 'mode main']
alt-ctrl-cmd-shift-j = ['join-with down', 'mode main']
alt-ctrl-cmd-shift-k = ['join-with up', 'mode main']
alt-ctrl-cmd-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

